{% set name = "cgns" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name|upper }}/{{ name|upper }}/archive/v{{ version }}.tar.gz
  sha256: 3B0615D1E6B566AA8772616BA5FD9CA4ECA1A600720E36EADD914BE348925FE2
  patches:
    - no-gui-apps.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('cgns', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - make  # [unix]
  host:
    - zlib
    - hdf5

test:
  commands:
    - cgnscheck
    - cgns_info  # from cgnstools/utilities

about:
  home: http://cgns.org
  license: Zlib
  license_file: LICENSE
  summary: CFD General Notation System (CGNS)
  description: |
    The CFD General Notation System (CGNS) provides a standard for
    recording and recovering computer data associated with the
    numerical solution of fluid dynamics equations.
  doc_url: http://cgns.github.io/CGNS_docs_current/index.html
  dev_url: https://github.com/CGNS/CGNS

extra:
  recipe-maintainers:
    - mdpiper
    - MicK7
