{% set name = "cgns" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name|upper }}/{{ name|upper }}/archive/v{{ version }}.tar.gz
  sha256: 090ec6cb0916d90c16790183fc7c2bd2bd7e9a5e3764b36c8196ba37bf1dc817

build:
  number: 4
  run_exports:
    - {{ pin_subpackage('cgns', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - make  # [unix]
  host:
    - zlib
    - hdf5

test:
  commands:
    - cgnscheck

about:
  home: http://cgns.org
  license: Zlib
  license_file: LICENSE
  summary: CFD General Notation System (CGNS)
  description: |
    The CFD General Notation System (CGNS) provides a standard for
    recording and recovering computer data associated with the
    numerical solution of fluid dynamics equations.
  doc_url: http://cgns.github.io/CGNS_docs_current/index.html
  dev_url: https://github.com/CGNS/CGNS

extra:
  recipe-maintainers:
    - mdpiper
    - MicK7
