travis:
  secure:
    BINSTAR_TOKEN: g9HdyKSiqvfLR/y5L920UYz9ZsqXQyPgJpJPGk8mw6189c1caYSNvn+eCTATVk/QpJm3Rr6NWmLjAMC9ij9fYmTACVy4cd+qypj5kNQJAHcN4muQg6ld1FO/x48BHFdQXaCF6ca4Rnm8itL/R9UljXKTRbwao+DiLFAmM8ccPPHD+YOtWkUsaPsiOpeA1yRc19sbHo8xILKrVnC7mnCB55FEHGEOWhQenfvAFZI6b+Xrx4NEXqhVWXV6s1mn3mBRZlvzQ9WICPNHxTfQDS7rH7/xXXGgXS5GTkqPHrPxFC8JYPlrDxVqtiXBlY43madiiDdsBzvyTJM/iI7z+g30T926mZBInFDgOzPLZ4AAY6RiXzJxZTAPhnyDuv0yyoAiwpiJjsPDFn9+TPKRuH88T2r9lrjcxiv/UZagTV6YZikQqbB03mDcw0baRr9RhsMyGqSQrvY3cKhH07etAu3UoHxJN0LpE8NwvaO6RAutALoMbsy/4tYBM/mWn/bMwTbyGWehsE8xucoTw0mJ03uUPbpHGfP7jPI8j/Rei8tiK72O7Rvmq3VOSt1kbVNR4Nul6zl96p5CqgSk9HjOdSNzZkTTOsqs82Z+SIv+ArfKdAXHUNzEf/KxMkPeBaur7iWiXB3yG6AIw6opii2hPRnw7eNQtM8lSkaR648jtkdSfJc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
